# Generated by Django 4.2.6 on 2023-10-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
