# Generated by Django 4.2.6 on 2023-10-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rating_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
